String teacherName = "Tess Løvgreen";
int daysInAYear = 365;
String dkHovedstad = "København";
boolean harCapPå = true;
int minutterPåEtDøgn = 60*24;
float tid200MeterLøb = 22.12;
String tessIntro = "Hej, jeg hedder " + teacherName;
boolean morgenPerson = false;
float newScore = 2.2 + 33;
char sTogKøge = 'S';  //Ved godt det ikke er "S" Linjen, men vi lader lige som om
